### ISSUE TITLE
Chrome with encoding problem

### ISSUE THREAD

**Issue by caeschfloh** [georgjaehnig/serchilo-drupal#170] opened 2017-04-04 15:28 UTC
I'm using ffi as default search engine in Chrome bar and it used to work greatly.
Now, when I search for a route from Köln to München, Chrome (Version 57.0.2987.133) encodes it like this:

r2r K%C3%B6ln%2C M%C3%BCnchen

As the Comma is also encoded, ffi even doesn't find the matching command.

Is this something that can be handled within the browser or do we need UTF8-reverse-encoding in a ffi-module? 

There is no issue in Firefox. I believe that Chrome is doing some heuristic auto-detection which fails in my case (I live overseas)
 ( https://productforums.google.com/forum/#!topic/chrome/2JIo6Yu7K-I;context-place=forum/chrome
https://bugs.chromium.org/p/chromium/issues/detail?id=597488 )

http://www.FindFind.it/n/de.deu.old-de.old-o.caeschfloh?query=%s could be flagged like this to ensure reverse-encoding:
http://www.FindFind.it/n/de.deu.old-de.old-o.caeschfloh?query=%s&revenc=1

**Comment by georgjaehnig** [comment] 2017-04-05 16:26
Thanks for your report, @caeschfloh! The problem should be fixed now.

It was caused by the [new SSL setup](https://twitter.com/findfind_it/status/846841873327149056) I made a few days ago. The Apache config got rewritten, and an important flag on the HTTP-HTTPS redirect got lost.

In fact, you could set up your URL to `https` (not `http`).

Plus, as you like to use your user commands from `caeschfloh`, the better way for doing this is the URL https://www.findfind.it/u/caeschfloh.

The namespaces to be used you can then set up at https://www.findfind.it/user/edit (when logged in).

**Closed by georgjaehnig** 2017-04-05 16:26 UTC
